Update packages
nachovigilante/react-7-segment-display pull request #1
Opened 2024-05-27 16:55 UTC by theaswanson

This PR updates the packages to their latest versions. Most notably, TypeScript gets upgraded from v4 to v5, and Storybook goes from v6 to v8.

I was having issues building this project and running Storybook on Windows, and these updates appear to fix that.

If there's anything you'd like me to change, please let me know!

2024-07-02 01:50 UTC, nachovigilante requested changes
I like the idea of updating the packages. Revert the changes on formatting and I'll accept it. Don't worry about the `/dist` directory, I'll remove it from the repo later. Thanks for investing time on this!

2024-07-02 01:50 UTC, nachovigilante commented on .prettierrc
Please don't change the default formatting rules

2024-07-02 01:50 UTC, nachovigilante commented on dist/cjs/components/Digit.d.ts
I left `/dist` folder by accident, it shouldn't be included in the repository. I'm sorry! :(

2024-07-03 00:45 UTC, theaswanson commented
@nachovigilante I've reverted the formatting and removed the changes to `dist`. Let me know what you think!

2024-07-03 21:20 UTC, nachovigilante approved these changes
Thanks for taking the time!

2024-07-03 21:21 UTC, merged